name: Build and Deploy a container to an Azure Container Instance

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: reCashflow.azurecr.io/cashflow:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create firebase.js file
        run: |
          echo "import { initializeApp } from 'firebase/app';" > src/firebase.js
          echo "import { getAuth } from 'firebase/auth';" >> src/firebase.js
          echo "import { getFirestore } from 'firebase/firestore';" >> src/firebase.js
          echo "import { getStorage } from 'firebase/storage';" >> src/firebase.js
          echo "const firebaseConfig = ${FIREBASE_CONFIG};" >> src/firebase.js
          echo "const app = initializeApp(firebaseConfig);" >> src/firebase.js
          echo "const auth = getAuth(app);" >> src/firebase.js
          echo "const db = getFirestore(app);" >> src/firebase.js
          echo "const storage = getStorage(app);" >> src/firebase.js
          echo "export { auth, db, storage };" >> src/firebase.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Build the application
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:latest .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create firebase.js file
        run: |
          echo "import { initializeApp } from 'firebase/app';" > src/firebase.js
          echo "import { getAuth } from 'firebase/auth';" >> src/firebase.js
          echo "import { getFirestore } from 'firebase/firestore';" >> src/firebase.js
          echo "import { getStorage } from 'firebase/storage';" >> src/firebase.js
          echo "const firebaseConfig = ${FIREBASE_CONFIG};" >> src/firebase.js
          echo "const app = initializeApp(firebaseConfig);" >> src/firebase.js
          echo "const auth = getAuth(app);" >> src/firebase.js
          echo "const db = getFirestore(app);" >> src/firebase.js
          echo "const storage = getStorage(app);" >> src/firebase.js
          echo "export { auth, db, storage };" >> src/firebase.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Run unit tests
        run: CI=true npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: myapp-${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:latest
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: cashflow
          location: 'westus'
          ports: |
            80
            443
          environment-variables: |
            NODE_ENV=production
          command: '["serve", "-s", "build", "-l", "80"]'
